language: cpp
sudo: required
dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux

addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake
env:
  global:
    - BUILD_TYPE: RELEASE
script: sh test.sh
